// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-image-service/pkg/isoeditor (interfaces: Editor)

// Package isoeditor is a generated GoMock package.
package isoeditor

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEditor is a mock of Editor interface.
type MockEditor struct {
	ctrl     *gomock.Controller
	recorder *MockEditorMockRecorder
}

// MockEditorMockRecorder is the mock recorder for MockEditor.
type MockEditorMockRecorder struct {
	mock *MockEditor
}

// NewMockEditor creates a new mock instance.
func NewMockEditor(ctrl *gomock.Controller) *MockEditor {
	mock := &MockEditor{ctrl: ctrl}
	mock.recorder = &MockEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditor) EXPECT() *MockEditorMockRecorder {
	return m.recorder
}

// CreateMinimalISOTemplate mocks base method.
func (m *MockEditor) CreateMinimalISOTemplate(arg0, arg1, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMinimalISOTemplate", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMinimalISOTemplate indicates an expected call of CreateMinimalISOTemplate.
func (mr *MockEditorMockRecorder) CreateMinimalISOTemplate(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMinimalISOTemplate", reflect.TypeOf((*MockEditor)(nil).CreateMinimalISOTemplate), arg0, arg1, arg2, arg3, arg4)
}

// ExtractNmstatectl mocks base method.
func (m *MockEditor) ExtractNmstatectl(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractNmstatectl", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractNmstatectl indicates an expected call of ExtractNmstatectl.
func (mr *MockEditorMockRecorder) ExtractNmstatectl(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractNmstatectl", reflect.TypeOf((*MockEditor)(nil).ExtractNmstatectl), arg0, arg1)
}

// CreateNmstateRamDisk mocks base method.
func (m *MockEditor) CreateNmstateRamDisk(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNmstateRamDisk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNmstateRamDisk indicates an expected call of CreateNmstateRamDisk.
func (mr *MockEditorMockRecorder) CreateNmstateRamDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNmstateRamDisk", reflect.TypeOf((*MockEditor)(nil).CreateNmstateRamDisk), arg0, arg1)
}